### ISSUE TITLE
why is says no isohdpfx.bin?

### ISSUE THREAD

**Issue by frankmeten** [tadas-s/custom-ubuntu-install#5]
I run on a ubuntu host, and I got the following message
xorriso : FAILURE : Given path does not exist on disk: -boot_image system_area='/usr/lib/ISOLINUX/isohdpfx.bin'

then I delete line which include isohdpfx.bin, I can build the iso successfully. But when I run vm, it says no root file system.
Appreciate if you can reply

**Comment by tadas-s** [comment]
Hi,
You need to make sure you have xorriso, p7zip-full, fakeroot, binutils, isolinux packages installed. By running this for example:

```
sudo apt-get install -y xorriso p7zip-full fakeroot binutils isolinux
```

`isohdpfx.bin` file specifically is part of `isolinux` package as far as I remember.

I also only tested this on Ubuntu 18.04.

**Comment by frankmeten** [comment]
> Hi,
> You need to make sure you have xorriso, p7zip-full, fakeroot, binutils, isolinux packages installed. By running this for example:
> 
> ```
> sudo apt-get install -y xorriso p7zip-full fakeroot binutils isolinux
> ```
> 
> `isohdpfx.bin` file specifically is part of `isolinux` package as far as I remember.
> 
> I also only tested this on Ubuntu 18.04.

Thank you for instant reply.  "sudo apt-get install isolinux" works.
btw, the customized iso is Ubuntu Desktop or Server version? or just a very basic Ubuntu?

**Comment by frankmeten** [comment]
> > Hi,
> > You need to make sure you have xorriso, p7zip-full, fakeroot, binutils, isolinux packages installed. By running this for example:
> > ```
> > sudo apt-get install -y xorriso p7zip-full fakeroot binutils isolinux
> > ```
> > 
> > 
> > `isohdpfx.bin` file specifically is part of `isolinux` package as far as I remember.
> > I also only tested this on Ubuntu 18.04.
> 
> Thank you for instant reply. "sudo apt-get install isolinux" works.
> btw, the customized iso is Ubuntu Desktop or Server version? or just a very basic Ubuntu?

I think it is desktop version.

**Comment by tadas-s** [comment]
> I think it is desktop version.

Well you can customize it by editing custom.cfg file. Generally you should read through it and modify to suit your needs.

https://github.com/tadas-s/custom-ubuntu-install/blob/master/custom.cfg#L9-L12
